### ISSUE TITLE
Hydration attribute mismatch

### ISSUE THREAD

**Issue by SoftWeb-Mike** [simplise/use-bootstrap#3]
Hi - I am using Nuxt for the first time, so please forgive me if this is a completely stupid question!

I have followed the given setup and installation within the docs and am just playing around with some concepts.
I have noticed, within the dev console, that there are a nmber of "Hydration attribute mismatch" warnings coming up, with the detail "this mismatch is check-only. The DOM will not be rectified in production due to performance overhead."

From the error and my v. limited knowledge of Nuxt - does this mean that the hydration could potentially fail in a production environment due to these miss matches?

I'm getting this error against pretty much every component, here is a single example:

```
Hydration attribute mismatch on <button type=​"button" id=​"nj6l49x6seu-1" class=​"btn" data-n-ids=​"{"nj6l49x6seu-0":​"nj6l49x6seu-1"}​">​…​</button>​ 
  - rendered on server: id="nj6l49x6seu-1"
  - expected on client: id="nt1E1ox8k6h_1"
  Note: this mismatch is check-only. The DOM will not be rectified in production due to performance overhead.
  You should fix the source of the mismatch. 
  at <HtmlButton class="btn" > 
  at <BsCardFooter> 
  at <BsCard> 
  at <BsGridCol class="my-2" key=0 > 
  at <BsGridRow columns="1 md-2 lg-3" > 
  at <BsGridContainer class="fluid" > 
```

**Comment by Iris-Fla** [comment]
@SoftWeb-Mike Thank you for your question.
This issue has been resolved in the latest version.Please update the module👍

`npm install usebootstrap@3.5.7`

If you have any questions, please contact us.
Thank you✨
