### ISSUE TITLE
Cannot find package 'ipx' imported from E:\RerainProject\RerainShow\.nuxt\dev\index.mjs 

### ISSUE THREAD

**Issue by persistencess** [simplise/use-bootstrap#4]
how to solve?
![t](https://github.com/user-attachments/assets/504742e9-1556-4c2e-8e3c-a4d4217ed0ff)

**Comment by KoujiSano** [comment]
Could you please provide the URL for StackBlitz or similar where I can review the entire project?

**Comment by persistencess** [comment]
> Could you please provide the URL for StackBlitz or similar where I can review the entire project?

ok，you can recreate a new nuxt3 project and then use the official provided steps，npm run 
the problem must appear

**Comment by persistencess** [comment]
> Could you please provide the URL for StackBlitz or similar where I can review the entire project?

But when I install @nuxt/image-edge then the error does not appear again

**Comment by persistencess** [comment]
You can add the @nuxt/image-edge dependency in official website description

**Comment by KoujiSano** [comment]
Could you please provide the URL where I can review the entire project where the issue is occurring? 
I checked with a new project but was unable to identify the problem.
