### ISSUE TITLE
[Suggestion] Everything with "b-..."?

### ISSUE THREAD

**Issue by dagnelies** [simplise/use-bootstrap#47]
Hi,
Thanks again for this nice library.
Now comes a suggestion: having all components start with "B", like "BAccordion" and "BAlert".

The reason to prefer this naming scheme has multiple benefits:

- it follows the same naming conventions as other libraries, for example:
   - https://bootstrap-vue.org/
   - https://bootstrap-vue-next.github.io/bootstrap-vue-next/
- it's easier to port that way
- it makes it easier to recognize directly if it's a bootstrap component or a self-made component. While this is usually not a problem in small personal projects, it's handy in larger grown ones to distinguish at a glance.
- you don't accidentally re-use the same name as an existing component

It's not must, merely a suggestion. Just ignore it if you don't like it.

**Comment by dagnelies** [comment]
I just discovered https://usebootstrap.org/lang-en/getting-started/customize 👍 

...perhaps it might be a good idea to set `'B'` as default there.

**Comment by KoujiSano** [comment]
It is a challenging issue to decide how to set the prefix for component names. 
Previously, we used to set the B prefix for all components, but we changed the default to no prefix for better readability. 
There might be a possibility of changing the default in the future.

**Comment by VividLemon** [comment]
Adding a prefix prevents the problem of single-word component names, making it more robust in the long run in case the HTML specification changes

**Comment by KoujiSano** [comment]
It is necessary to clearly document that prefixes can be added via settings.

**Comment by KoujiSano** [comment]
We plan to add prefixes during the major version update.

**Comment by KoujiSano** [comment]
As a temporary measure, both the empty prefix and the 'B' prefix will be supported. 
The documentation will be updated to reflect the use of the 'B' prefix. 
In the future, support for the empty prefix may be discontinued.

**Comment by dagnelies** [comment]
Pragmatic and efficient 👍

**Comment by KoujiSano** [comment]
Support was completed in version 3.5.95.
