### ISSUE TITLE
How to bind to "native" bootstrap elements events? Specifically in my case I want to be able to capture `hide.bs.modal` event.

### ISSUE THREAD

**Issue by caiohamamura** [simplise/use-bootstrap#5]
I would like to be able to bind to the bootstrap "native" element's event such as `Modal` `hide.bs.modal` to be able to perform my custom function whenever the modal is closed no matter how it was closed (click outside, click button, click X).

How would I achieve that, as I'm unable to know the true local id (because it is assigned randomly) for being able to `addEventListener`? The `<Modal ref=...>` does not work either because the object is not the native `new bootstrap.Modal()` either.

If there is no actual solution to this meanwhile, I would suggest that `<Element ref=[...]>` return the "native" `new bootstrap.[...]`, instead of returning a custom object with limited capabilities so the user can access to whatever functions are available to `bootstrap` regular library. Is it possible?

**Comment by caiohamamura** [comment]
Reading the source code I found out a way to do that, but it is kind of weird because the name of the emitted event is `hide.modal`, because it has a `.` so we cannot directly use `@hide.modal` but we have to use something like:

```
<Modal v-on="{'hide.modal': ModalHiddenFunction}>
```

I wonder this shoud be renamed to `modal:hide`, I think this is a nice pattern `modal:hide`, `accordion:changed`. Is this planned to be documented, or is it already? I didn't find it.

**Comment by KoujiSano** [comment]
[追加が必要なページ events](http://localhost:3000/lang-en/getting-started/events)

**Comment by KoujiSano** [comment]
Supported in version 3.5.22. 
Here is the demo code: 

[event](https://usebootstrap.org/lang-en/getting-started/events)
[modal](https://usebootstrap.org/lang-en/components/modal)
